name: PR Title Checker

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 許可するTypeを指定
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
          # スコープは必須にしない
          requireScope: false
